[versions]
# Plugin versions
gremlin = "0.0.9"
minotaur = "2.9.0"
resourceFactory = "1.3.1"
runTask = "3.0.2"
shadow = "9.2.2"

# Dependency versions
dazzleconf = "2.0.0-M1"
discordsrv = "1.28.0"
jakarta-inject = "2.0.1"
openinv = "5.3.0"
paper = "1.21.11-R0.1-SNAPSHOT"
placeholderapi = "2.12.2"
solidinjector = "1.1.0-RC2"

[plugins]
gremlin = { id = "xyz.jpenilla.gremlin-gradle", version.ref = "gremlin" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
resourceFactory-paperConvention = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resourceFactory" }
runTask-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runTask" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
dazzleconf-core = { group = "space.arim.dazzleconf", name = "dazzleconf-core", version.ref = "dazzleconf" }
dazzleconf-yaml = { group = "space.arim.dazzleconf", name = "dazzleconf-yaml", version.ref = "dazzleconf" }
discordsrv = { group = "com.discordsrv", name = "discordsrv", version.ref = "discordsrv" }
jakarta-inject = { group = "jakarta.inject", name = "jakarta.inject-api", version.ref = "jakarta-inject" }
openinv = { group = "com.github.Jikoo", name = "OpenInv", version.ref = "openinv" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
solidinjector = { group = "space.arim.injector", name = "injector", version.ref = "solidinjector" }